### ISSUE TITLE
soccer video

### ISSUE THREAD

**Issue by juvien** [cioppaanthony/context-aware-loss#1]
can you will give a demo scirip ,like input  a soccer vedio ，output some scenes at different timestamps? btw, how long this repo will release? thanks

**Comment by cioppaanthony** [comment]
Hi, thanks for your comment. 

In this first version, we will release the code for training and testing only on the pre-computed features of SoccerNet (ResNet, C3D, I3D). The main goal of this repository is to reproduce the results of the paper. 

It is not excluded that some day we will add more features to this code, if there is a demand for it, but it is not the priority right now. First, we want to make sure that people are able to use our code and reproduce our results. Any feedback will be appreciated !

To answer your last question, it should not be long until we release the code on this repository. I can not give you an exact date, but it should arrive within the next two weeks I hope.

**Comment by juvien** [comment]
ok,it means if i want to use this model  on some other videos, first i need the three (ResNet, C3D, I3D)model to extract features,then input this model? as far as i know ,anyway,so expect!

**Comment by cioppaanthony** [comment]
You will first need to extract the features of the video at 2 frames per second with one of the three networks: ResNet, C3D or I3D as was done in the original SoccerNet paper. 

Our best results were obtained with the ResNet_PCA512 features (see original SoccerNet paper for details on how to extract these features for the video: [SoccerNet](https://arxiv.org/abs/1804.04527)). 

Note that we will release our trained weights for the ResNet_PCA512 features for which we got the 62.5% Average-mAP. So you won't need to re-train the network yourself if you only want to test it.

**Comment by juvien** [comment]
well ,make sure that: it means that if i want to test on my video,first i extract the features of the video at 2 frames per second with one of the three networks: ResNet, C3D or I3D .
ResNet_PCA512 features  is the the ResNet and PAC model get.  er...next ,these features put what model get the results? this repo will introduce?

**Comment by juvien** [comment]
also  today  i will read these two papers for more informations.thanks, i  can't wait to know the anwers

**Comment by cioppaanthony** [comment]
I will try to see if we can easily include the code for computing these features (ResNet_PCA512 for example) from the video file to this repository.

**Comment by juvien** [comment]
hello,so expect your pre_train model and code ,how long i should wait?
